// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates an image based on keywords selected by the user.
 *
 * - generateImage - A function that generates an image from keywords.
 * - GenerateImageInput - The input type for the generateImage function.
 * - GenerateImageOutput - The return type for the generateImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateImageInputSchema = z.object({
  keywords: z.array(z.string()).describe('An array of keywords to generate an image from.'),
});
export type GenerateImageInput = z.infer<typeof GenerateImageInputSchema>;

const GenerateImageOutputSchema = z.object({
  image: z.string().describe('The generated image as a data URI.'),
});
export type GenerateImageOutput = z.infer<typeof GenerateImageOutputSchema>;

export async function generateImage(input: GenerateImageInput): Promise<GenerateImageOutput> {
  return generateImageFlow(input);
}

const imageGenerationPrompt = ai.definePrompt(
  {
    name: 'wackyImagePrompt',
    input: { schema: GenerateImageInputSchema },
    prompt: `A {{#each keywords}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}, in a wacky and fun style.`,
  },
);

const generateImageFlow = ai.defineFlow(
  {
    name: 'generateImageFlow',
    inputSchema: GenerateImageInputSchema,
    outputSchema: GenerateImageOutputSchema,
  },
  async input => {
    const {media} = await ai.generate({
      // IMPORTANT: ONLY the googleai/gemini-2.0-flash-preview-image-generation model is able to generate images. You MUST use exactly this model to generate images.
      model: 'googleai/gemini-2.0-flash-preview-image-generation',

      prompt: await imageGenerationPrompt(input),

      config: {
        responseModalities: ['TEXT', 'IMAGE'], // MUST provide both TEXT and IMAGE, IMAGE only won't work
      },
    });

    return {image: media!.url!};
  }
);
